name: Upload to CurseForge

on:
    push:
        branches:
            - main

jobs:
    upload-addon:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get repository name
              run: echo "repo_name=$(basename ${{ github.repository }})" >> $GITHUB_ENV

            - name: Extract version and game versions
              run: |
                  # Versión principal desde el .toc principal
                  version=$(grep -Po "(?<=## Version: )\d+\.\d+\.\d+" ${{ env.repo_name }}.toc)
                  echo "addon_version=$version" >> $GITHUB_ENV

                  # Recolectar TODAS las interfaces de los .toc
                  interfaces=$(grep -rhPo "(?<=## Interface: )\d+" . | sort -u)

                  # Convertir interfaces a versiones de juego (X.Y.Z)
                  game_versions=""
                  for interface in $interfaces; do
                      major=$((interface / 10000))
                      minor=$(( (interface % 10000) / 100 ))
                      patch=$((interface % 100))
                      game_versions+="${major}.${minor}.${patch},"
                  done

                  # Remover última coma y guardar
                  game_versions=${game_versions%?}
                  echo "game_versions=$game_versions" >> $GITHUB_ENV

            - name: Prepare addon folder
              run: |
                  mkdir "${{ env.repo_name }}"
                  rsync -av --progress ./* "${{ env.repo_name }}/" \
                      --exclude ".git*" \
                      --exclude ".github*" \
                      --exclude "README.md" \
                      --exclude "CHANGELOG.md" \
                      --exclude "${{ env.repo_name }}"

            - name: Create addon ZIP
              run: |
                  zip -r "${{ env.repo_name }}-${{ env.addon_version }}.zip" "${{ env.repo_name }}"

            - name: Read CHANGELOG.md
              run: |
                  changelog=$(cat CHANGELOG.md)
                  echo "changelog=$changelog" >> $GITHUB_ENV

            - name: Upload to CurseForge
              uses: itsmeow/curseforge-upload@v3.1.2
              with:
                  token: ${{ secrets.CURSEFORGE_API_KEY }}
                  project_id: ${{ secrets.CURSEFORGE_PROJECT_ID }}
                  game_endpoint: "wow"
                  game_versions: "${{ env.game_versions }}" # Todas las versiones detectadas
                  file_path: "${{ env.repo_name }}-${{ env.addon_version }}.zip"
                  changelog: "${{ env.changelog }}"
                  changelog_type: markdown
                  release_type: release
